version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=cicd
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=cicd
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  db-data:
